AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Spring Boot + AWS Lambda demo project

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Resources:
  LetMeDoWithDev:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.LetMeDoWith.LetMeDoWith.common.handler.LambdaStreamHandler::handleRequest
      Runtime: java17
      CodeUri: .
      Architectures:
        - x86_64
      MemorySize: 2048
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 600
      SnapStart:
        ApplyOn: PublishedVersions
      AutoPublishAlias: prod
      Events:
        LetMeDoWithDevApiGw:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          DB_URL: localhost

Outputs:
  LetMeDoWithDevApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com'
    Export:
      Name: LetMeDoWithDevApi