spring:
  profiles:
    default: dev
    group:
      "local": "local, local-confidential"
      "dev": "dev, dev-confidential"
      "prod": "prod, prod-confidential"

server:
  port: 8080
  error:
    include-stacktrace: always

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/letmedowith_app
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    enabled: true
    url: jdbc:mysql://localhost:3306/letmedowith_app

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace
    com.LetMeDoWith.LetMeDoWith: debug
    root: debug

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # TODO - 변경 필요
    url: jdbc:mysql://localhost:3306/letmedowith_app # TODO - 변경 필요
  data:
    redis:
      host: localhost # TODO - 변경 필요
      port: 6379 # TODO - 변경 필요
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    enabled: true
    url: jdbc:mysql://localhost:3306/letmedowith_app

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace
    com.LetMeDoWith.LetMeDoWith: debug
    root: debug



---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/letmedowith_app
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true