version: '3'
services:
  mysql-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: letmedowith_db_adm
      MYSQL_DATABASE: letmedowith_app
      MYSQL_USER: letmedowith
      MYSQL_PASSWORD: letmedowith@admin#2024
    networks:
      - LMDW
    volumes:
      - mysql-data:/var/lib/mysql
      # Mount the external volume for MySQL data storage
      # Mount the SQL script for initialization

  redis-server:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - LMDW

networks:
  LMDW:
    driver: bridge

volumes:
  mysql-data:
  redis-data: